export const projects = [
  {
    name: "Frases aleatorias",
    img: "frasesAleatorias.png",
    git: "https://github.com/adiazt01/frases-aleatorias",
    info: "En este proyecto se pone a prueba la obtencion de datos de una API en React para generar frases aleatorias.",
    link: "https://adiazt01.github.io/frases-aleatorias/",
    techs: ["React", "HTML/CSS"],
  },
  {
    name: "Landing Page",
    img: "landingPageReact.png",
    git: "https://github.com/adiazt01/lp-react",
    info: "Una landing para una empresa que presta  servicios como desarrolladora de videojuegos.",
    link: "https://adiazt01.github.io/lp-react/",
    techs: ["React","Sass","HTML/CSS"],
  },
  {
    name: "Button Component",
    img: "ButtonComponent.png",
    git: "https://github.com/adiazt01/button-component",
    info: "En este proyecto en este proyectos se tiene como objetivo la reutilizacion de un mismo componente que mediantte sus props puede alterar el estilo del componente, en este caso un boton.",
    link: "https://adiazt01.github.io/button-component/",
    techs: ["React", "HTML/CSS"],
  },
  {
    name: "Calculadora",
    img: "calculadora.png",
    git: "https://github.com/adiazt01/calculadora",
    info: "Una calculadora que permite realizar operaciones basicas.",
    link: "https://adiazt01.github.io/calculadora/",
    techs: ["React", "HTML/CSS"],
  },
  {
    name: "Pagina 404",
    img: "page404.png",
    git: "https://github.com/adiazt01/page404",
    info: "Una simple pagina que muestra un 404",
    link: "https://adiazt01.github.io/page404/",
    techs: ["HTML/CSS"],
  },
];
